### ISSUE TITLE
Error runing silvie

### ISSUE THREAD

**Issue by esmaily** [hmak-me/silvie#11]
after install silvie when run app occurred  this error
`
'nodemon' is not recognized as an internal or external command,
operable program or batch file.

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at notFoundError (H:\projects\js-lib\silive-test-app\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (H:\projects\js-lib\silive-test-app\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (H:\projects\js-lib\silive-test-app\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (H:\projects\js-lib\silive-test-app\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn nodemon',
  path: 'nodemon',
  spawnargs: [
    '--exec',
    'babel-node',
    '--watch',
    'src',
    'src/bootstrap/index.ts',
    '--',
    '-x',
    '.ts,.js',
    '--config-file',
    'H:\\projects\\js-lib\\silive-test-app\\node_modules\\silvie\\assets\\babel.config.js'
  ]
}
`

**Comment by hmak-dev** [comment]
There was a missing 'nodemon' package in the project dependencies. It is now included in the hotfix update on npm repo. Please update your local instance to the latest version to resolve this issue. If you are still experiencing this problem, please provide more information about what you get.
